on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_job:
    name: DailyQuote Runner
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies (if needed)
      run: |
        cd source
    - name: Run app.py
      run: |
        cd source
        python app.py
    - name: Commit changes
      run: |
        git remote set-url origin https://$GITHUB_REPOSITORY_OWNER:$PAT@github.com/$GITHUB_REPOSITORY
        git config --global user.name "DailyQuote Update [Workflow]"
        git config --global user.email '55059632+Azio0@users.noreply.github.com'
        git add -A
        git commit -m 'Update QUOTE.md with a daily quote'
        git push
